#!/bin/bash

# generate-secrets.sh
# Generates Kubernetes secrets.yaml from environment variables
# DO NOT commit the generated secrets.yaml file!

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
NAMESPACE="${NAMESPACE:-mcp-agent-dev}"
OUTPUT_FILE="${OUTPUT_FILE:-k8s/config/secrets.yaml}"

echo -e "${GREEN}Generating Kubernetes secrets from environment variables...${NC}"
echo ""

# Check required environment variables
MISSING_VARS=()

if [ -z "$DD_API_KEY" ]; then
  MISSING_VARS+=("DD_API_KEY")
fi

if [ -z "$OPENAI_API_KEY" ]; then
  MISSING_VARS+=("OPENAI_API_KEY")
fi

# Report missing variables
if [ ${#MISSING_VARS[@]} -ne 0 ]; then
  echo -e "${RED}ERROR: Missing required environment variables:${NC}"
  for var in "${MISSING_VARS[@]}"; do
    echo -e "  ${RED}✗${NC} $var"
  done
  echo ""
  echo -e "${YELLOW}Please set these variables before running this script:${NC}"
  echo "  export DD_API_KEY='your-datadog-api-key'"
  echo "  export OPENAI_API_KEY='your-openai-api-key'"
  echo ""
  exit 1
fi

echo -e "${GREEN}✓${NC} All required environment variables are set"
echo ""

# Base64 encode the secrets (required for Kubernetes secrets)
DD_API_KEY_B64=$(echo -n "$DD_API_KEY" | base64)
OPENAI_API_KEY_B64=$(echo -n "$OPENAI_API_KEY" | base64)

# Optional: Vertex AI key
if [ -n "$VERTEX_AI_KEY" ]; then
  VERTEX_AI_KEY_B64=$(echo -n "$VERTEX_AI_KEY" | base64)
  echo -e "${GREEN}✓${NC} VERTEX_AI_KEY found (optional)"
else
  VERTEX_AI_KEY_B64=""
  echo -e "${YELLOW}ℹ${NC} VERTEX_AI_KEY not set (optional)"
fi

# Optional: GCP Service Account Key (should be a JSON file path)
if [ -n "$GCP_SA_KEY_FILE" ] && [ -f "$GCP_SA_KEY_FILE" ]; then
  GCP_SA_KEY_B64=$(base64 < "$GCP_SA_KEY_FILE" | tr -d '\n')
  echo -e "${GREEN}✓${NC} GCP_SA_KEY_FILE found (optional)"
elif [ -n "$GCP_SA_KEY_JSON" ]; then
  GCP_SA_KEY_B64=$(echo -n "$GCP_SA_KEY_JSON" | base64)
  echo -e "${GREEN}✓${NC} GCP_SA_KEY_JSON found (optional)"
else
  GCP_SA_KEY_B64=""
  echo -e "${YELLOW}ℹ${NC} GCP Service Account Key not set (optional)"
fi

echo ""
echo -e "${GREEN}Generating secrets file: ${OUTPUT_FILE}${NC}"

# Generate the secrets.yaml file
cat > "$OUTPUT_FILE" <<EOF
# AUTO-GENERATED FILE - DO NOT COMMIT TO VERSION CONTROL
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Generated by: k8s/scripts/generate-secrets.sh
#
# This file contains base64-encoded secrets.
# To regenerate: ./k8s/scripts/generate-secrets.sh

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: $NAMESPACE
  labels:
    app: mcp-agent
    environment: dev
    managed-by: script
type: Opaque
data:
  # Datadog API Key (base64 encoded)
  datadog-api-key: $DD_API_KEY_B64

  # OpenAI API Key (base64 encoded)
  openai-api-key: $OPENAI_API_KEY_B64
EOF

# Add optional secrets if they exist
if [ -n "$VERTEX_AI_KEY_B64" ]; then
  cat >> "$OUTPUT_FILE" <<EOF

  # Vertex AI Key (base64 encoded)
  vertex-ai-key: $VERTEX_AI_KEY_B64
EOF
fi

if [ -n "$GCP_SA_KEY_B64" ]; then
  cat >> "$OUTPUT_FILE" <<EOF

  # GCP Service Account Key JSON (base64 encoded)
  gcp-sa-key: $GCP_SA_KEY_B64
EOF
fi

# Add final newline
echo "" >> "$OUTPUT_FILE"

echo -e "${GREEN}✓${NC} Secrets file generated successfully!"
echo ""
echo -e "${YELLOW}IMPORTANT SECURITY NOTES:${NC}"
echo -e "  1. The file ${RED}$OUTPUT_FILE${NC} contains real secrets"
echo -e "  2. This file is in ${GREEN}.gitignore${NC} and will NOT be committed"
echo -e "  3. ${RED}DO NOT${NC} manually add this file to git"
echo -e "  4. Each team member should generate their own secrets file"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  Apply secrets to your cluster:"
echo -e "    ${YELLOW}kubectl apply -f $OUTPUT_FILE${NC}"
echo ""
echo "  Or use the deployment script:"
echo -e "    ${YELLOW}./k8s/scripts/deploy.sh${NC}"
echo ""
